#!/bin/bash

curl -s -c coo.txt 138.68.189.41:32381 | grep -oP "(?<=h3 align='center'>).*(?=</h3)" | tr -d "\n" | md5sum | awk '{print "hash="$1}' | curl -s -b coo.txt -X POST -d @- 138.68.189.41:32381 | grep -oP "(?<=<p align='center'>).*(?=</p>)"
